import requests
from bs4 import BeautifulSoup
# THIS IS THE WEB SCRAPPING
url = "https://ufm.edu/Estudios"
html_doc = requests.get(url)
# THIS CREATES THE SOUP OBJECT
soup = BeautifulSoup(html_doc.text,'html.parser')
a_tag = soup.find_all("a",limit = 8)
a_tag28 = soup.find_all("a")
a_tag100 = soup.find_all("a",limit = 100)
a_tag150 = soup.find_all("a",limit = 300)
print ("2.estudios")
def finder(tag,keye):
    cont = 0
    for i in tag :
        if i.text == keye:
            print("------------------------")
            print(keye," links to ",i['href'])
            
        
print("")
print("top bar icons are: ")
finder(a_tag,"UFM Key Projects")
finder(a_tag,"Friends of UFM")
finder(a_tag,"Donaciones")
finder(a_tag,"Contáctenos")
finder(a_tag,"Admisiones")
finder(a_tag,"Alumni")
finder(a_tag,"Campus Madrid")
finder(a_tag,"Redes Sociales")
print("")
print("Doctorados son:")
finder(a_tag28,"Programa de Doctorado")
print("Maestrias son:")
finder(a_tag28,"MBA in Entrepreneurship")
finder(a_tag28,"Arbitraje Internacional")
finder(a_tag28,"Ciencias Sociales")
finder(a_tag28,"Génetica Molecular Humana")
finder(a_tag28,"Psicología Médica Integral")
finder(a_tag28,"MBA")
finder(a_tag28,"MBA Virtual")
finder(a_tag28,"MFIN")
finder(a_tag28,"MAPI")
finder(a_tag28,"LLM")
finder(a_tag28,"MEE")
finder(a_tag28,"ME")
finder(a_tag28,"Diabetes y Síndrome Metabólico")
finder(a_tag28,"Enfermedad Renal Crónica y Síndrome")
finder(a_tag28,"Metabólico")
finder(a_tag28,"Filosofía")
finder(a_tag28,"Historia")
finder(a_tag28,"Lingüistica")
finder(a_tag28,"Objetivismo")
finder(a_tag28,"Política Económica Internacional")
finder(a_tag28,"Política y Derecho Internacional")       
finder(a_tag28,"Relaciones internacionales")
finder(a_tag28,"Endodoncia")
finder(a_tag28,"Ortodoncia")
finder(a_tag28,"Rehabilitación Oral y Odontología Cosmética")
finder(a_tag28,"Periodoncia e Implantes Dentales")
print("")
print("posgrados son: ")
finder(a_tag28,"Dermatología")
finder(a_tag28,"Hemato-Oncología Pediátrica")
finder(a_tag28,"Medicina Interna")
finder(a_tag28,"Oftalmología")
finder(a_tag28,"Historia")
finder(a_tag28,"Lingüística")
print("")
print("left bar icons are")
finder(a_tag100,"Biblioteca")
finder(a_tag100,"New Media")
finder(a_tag100,"Calendario")
finder(a_tag100,"Directorio")
print("")
print("a_tag length is:",len(a_tag28))
print("")
print("links to social media are: ")
finder(a_tag150," Facebook")
finder(a_tag150," Twitter")
finder(a_tag150," Linkedin")



