import requests
from bs4 import BeautifulSoup
# THIS IS THE WEB SCRAPPING
url = "https://ufm.edu/Estudios"
html_doc = requests.get(url)
# THIS CREATES THE SOUP OBJECT
soup = BeautifulSoup(html_doc.text,'html.parser')
a_tag = soup.find_all("a",limit = 8)
a_tag28 = soup.find_all("a")
a_tag100 = soup.find_all("a",limit = 100)
a_tag150 = soup.find_all("a",limit = 300)
print ("2.estudios")
def finder(tag,keye):
    for i in tag :
        if i.text == keye:
            print("--------------------------------------------------------------------------------------")
            print(keye," links to ",i['href'])
f = open("estudios.txt","w+")
def finder_txt(tag,keye):
    for i in tag :
        if i.text == keye:
            f.write("--------------------------------------------------------------------------------------------------------")
            f.write('\n')
            f.write(i['href'])
            f.write('\n')
            
        
print("")
print("top bar icons are: ")
finder(a_tag,"UFM Key Projects")
finder(a_tag,"Friends of UFM")
finder(a_tag,"Donaciones")
finder(a_tag,"Contáctenos")
finder(a_tag,"Admisiones")
finder(a_tag,"Alumni")
finder(a_tag,"Campus Madrid")
finder(a_tag,"Redes Sociales")
print("")
print("IMPRIMIENDO ESTUDIOS A ESTUDIOS.TXT")
print("")
f.write("Doctorados son:")
f.write('\n')
finder_txt(a_tag28,"Programa de Doctorado")
f.write("")
f.write("Maestrias son:")
f.write('\n')
finder_txt(a_tag28,"MBA in Entrepreneurship")
finder_txt(a_tag28,"Arbitraje Internacional")
finder_txt(a_tag28,"Ciencias Sociales")
finder_txt(a_tag28,"Génetica Molecular Humana")
finder_txt(a_tag28,"Psicología Médica Integral")
finder_txt(a_tag28,"MBA")
finder_txt(a_tag28,"MBA Virtual")
finder_txt(a_tag28,"MFIN")
finder_txt(a_tag28,"MAPI")
finder_txt(a_tag28,"LLM")
finder_txt(a_tag28,"MEE")
finder_txt(a_tag28,"ME")
finder_txt(a_tag28,"Diabetes y Síndrome Metabólico")
finder_txt(a_tag28,"Enfermedad Renal Crónica y Síndrome")
finder_txt(a_tag28,"Metabólico")
finder_txt(a_tag28,"Filosofía")
finder_txt(a_tag28,"Historia")
finder_txt(a_tag28,"Lingüistica")
finder_txt(a_tag28,"Objetivismo")
finder_txt(a_tag28,"Política Económica Internacional")
finder_txt(a_tag28,"Política y Derecho Internacional")       
finder_txt(a_tag28,"Relaciones internacionales")
finder_txt(a_tag28,"Endodoncia")
finder_txt(a_tag28,"Ortodoncia")
finder_txt(a_tag28,"Rehabilitación Oral y Odontología Cosmética")
finder_txt(a_tag28,"Periodoncia e Implantes Dentales")
f.write("\n")
f.write("posgrados son: ")
f.write('\n')
finder_txt(a_tag28,"Dermatología")
finder_txt(a_tag28,"Hemato-Oncología Pediátrica")
finder_txt(a_tag28,"Medicina Interna")
finder_txt(a_tag28,"Oftalmología")
finder_txt(a_tag28,"Historia")
finder_txt(a_tag28,"Lingüística")
f.write("\n")
f.write("licenciaturas son: ")
f.write('\n')
finder_txt(a_tag28,"Administración de Empresas")
finder_txt(a_tag28,"Finanzas")
finder_txt(a_tag28,"Mercadeo")
finder_txt(a_tag28,"Arquitectura")
finder_txt(a_tag28,"Ciencia Política")
finder_txt(a_tag28,"Comercio Exterior")
finder_txt(a_tag28,"Comunicación y Periodismo")
finder_txt(a_tag28,"Políticas Públicas")
finder_txt(a_tag28,"Gestión de Proyectos")
finder_txt(a_tag28,"Contaduría Pública y Auditoría (CPA)")
finder_txt(a_tag28,"Derecho")
finder_txt(a_tag28,"Diseño de Producto")
finder_txt(a_tag28,"Diseño Digital Interactivo")
finder_txt(a_tag28,"Economía")
finder_txt(a_tag28,"Data Science")
finder_txt(a_tag28,"Politics and Philosophy")
finder_txt(a_tag28,"Educación y Emprendimiento")
finder_txt(a_tag28,"Enseñanza de la Historia")
finder_txt(a_tag28,"Entrepreneurship and Business")
finder_txt(a_tag28,"Escuela de Cine y Artes Visuales")
finder_txt(a_tag28,"BA en Cine, Artes Visuales y Emprendimiento")       
finder_txt(a_tag28,"Ingeniería Empresarial")
finder_txt(a_tag28,"Ingeniería en Computer Science")
finder_txt(a_tag28,"Lengua y Literatura")
finder_txt(a_tag28,"Medicina")
finder_txt(a_tag28,"Nutrición Clínica")

print("left bar icons are:")
finder(a_tag100,"Biblioteca")
finder(a_tag100,"New Media")
finder(a_tag100,"Calendario")
finder(a_tag100,"Directorio")
print("")
print("a_tag length is:",len(a_tag28))
print("")
print("links to social media are: ")
finder(a_tag150," Facebook")
finder(a_tag150," Twitter")
finder(a_tag150," Linkedin")



